version: '3'
services:
  web:
    build: .
    ports:
      - 3000
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    deploy:
      replicas: 3
    networks:
    - mynetwork
  nginx:
    image: nginx
    restart: "always"
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - mynetwork
  # cache:
  #   image: redis:alpine
  #   ports:
  #     - 6380:6379
  # db:
  #   image: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=Bao@2022
  #     - MYSQL_DATABASE=testdb
  #   ports:
  #     - 3309:3306
volumes:
  db:
networks:
  mynetwork: